TinTucCTSV/Models/Regency/RegencyIndexModel.cs
using System.Collections.Generic;
namespace TinTucCTSV.Models.Regency
{
    public class RegencyIndexModel
    {
        public IEnumerable<RegencyViewModel> ListRegencies{ get; set; }
    }
}

TinTucCTSV/Models/Regency/RegencyNewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TinTucCTSV.Models.Regency
{
    public class RegencyNewModel
    {
        [Display(Name = "Id")]
        public string Id { get; set; }
        
        [Required]
        [Display(Name = "Tên chức vụ")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Mô tả")]
        public string Description { get; set; }
    }
}

TinTucCTSV/Models/Regency/RegencyUpdateModel.cs
using System.ComponentModel.DataAnnotations;
namespace TinTucCTSV.Models.Regency
{
    public class RegencyUpdateModel
    {
        public string Id { get; set; }
        [Display(Name="Tên chức vụ")]
        public string Name { get; set; }
    }
}

TinTucCTSV/Models/Regency/RegencyViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace TinTucCTSV.Models.Regency
{
    public class RegencyViewModel
    {
        [Display(Name = "Mã Chức vụ")]
        public string Id { get; set; }

        [Display(Name = "Tên Chức vụ")]
        public string Name { get; set; }

        [Display(Name = "Mô tả")]
        public string Description { get; set; }
    }
}

TinTucCTSV/Areas/Admin/Controllers/RegencyController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TinTucCTSV.Data.Interfaces;
using TinTucCTSV.Data.Models;
using TinTucCTSV.Models.Regency;

namespace TinTucCTSV.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrator")]
    public class RegencyController : Controller
    {
        private readonly IRegency _regencyService;
        public RegencyController(IRegency regencyService){
           _regencyService = regencyService;
        }

        public IActionResult Index(){
            var regencies = _regencyService.GetAll().Select(regency => new RegencyViewModel{
                Id = regency.Id,
                Name = regency.Name,
                Description = regency.Description
            });
            var model = new RegencyIndexModel{
                ListRegencies = regencies
            };
            return View(model);
        }

        //Create Regency
        public IActionResult Create(){
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRegency(RegencyNewModel model){
            if (ModelState.IsValid)
            {
                var regency = new Regency{
                    Name = model.Name,
                    Description = model.Description
                };
                await _regencyService.Add(regency);
            }
            return RedirectToActionPermanent(nameof(Index));
        }

        //Delete Regency
        public async Task<IActionResult> Delete(string Id){
            await _regencyService.Delete(Id);
            return RedirectToActionPermanent(nameof(Index));
        }

        //Edit Regency
        public IActionResult Update(string Id){
            var regency = _regencyService.GetById(Id);
            var result = new RegencyUpdateModel{
                Id = regency.Id,
                Name = regency.Name
            };
            return View(result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateRegency(string Id,RegencyUpdateModel model){
            if (ModelState.IsValid)
            {
                await _regencyService.Edit(Id,model.Name);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToActionPermanent(nameof(Update));
        }
    }
}

TinTucCTSV/Areas/Admin/Views/Regency/Create.cshtml
@model TinTucCTSV.Models.Regency.RegencyNewModel
@{
    ViewData["Title"] = "Tạo chức vụ";
}
    <form asp-controller="Regency" asp-action="CreateRegency">
        <h1>Tạo chức vụ mới</h1>
        <br/>
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" ></span>
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" ></span>
        </div>
        <input type="submit" value="Create" class="btn btn-success"/>
    </form>

TinTucCTSV/Areas/Admin/Views/Regency/Index.cshtml
@model TinTucCTSV.Models.Regency.RegencyIndexModel
@{
    ViewData["Title"] = "Chức vụ";
}
<partial name="_TaskbarPartial"/>
<div class="container">
    <table class="table .table-bordered table-responsive">
        <thead>
            <tr>
                <!-- <th>
                    @Html.DisplayNameFor(department =>department.ListRegencies.FirstOrDefault().Id)
                </th> -->
                <th>
                    @Html.DisplayNameFor(department =>department.ListRegencies.FirstOrDefault().Name)
                </th>
                <th>
                    @Html.DisplayNameFor(department =>department.ListRegencies.FirstOrDefault().Description)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var regency in @Model.ListRegencies)
            {
                <tr>
                    <!-- <td>
                        @regency.Id
                    </td> -->
                    <td>
                        @regency.Name
                    </td>
                    <td>
                        @regency.Description
                    </td>
                    <td>
                        <partial name="_ButtonStringPartial" model="@regency.Id" />
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

TinTucCTSV/Areas/Admin/Views/Regency/Update.cshtml
@model TinTucCTSV.Models.Regency.RegencyUpdateModel
@{
    ViewData["Title"] = @Model.Name;
}
<h1>Chỉnh sửa chức vụ</h1>
        <br/>
<div>
    <div>
        <form asp-action="UpdateRegency">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden"/>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" value="@Model.Name" class="form-control"/>
                <span asp-validation-for="Name"></span>
            </div>
            <div class="from-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>